# Generated by Django 5.2.5 on 2025-08-17 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_date', models.DateField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.achievement')),
            ],
            options={
                'verbose_name': 'Achievement record',
                'verbose_name_plural': 'Achievement records',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('achievements', models.ManyToManyField(blank=True, related_name='employees', through='dp.AchievementEmployee', to='dp.achievement')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='dp.department')),
            ],
        ),
        migrations.AddField(
            model_name='achievementemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_links', to='dp.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='achievementemployee',
            unique_together={('achievement', 'employee', 'achievement_date')},
        ),
    ]
